services:
  - type: web
    name: ectracc-backend
    env: node
    plan: free
    rootDir: ./ectracc-backend
    buildCommand: npm install
    startCommand: node --max-old-space-size=400 index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://patrickahern93_db_user:MxRIg6Jop0nK6qay@cluster0.wxqzvqa.mongodb.net/ectracc?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DATABASE
        value: ectracc
      - key: SUPABASE_URL
        value: https://your-project-id.supabase.co
      - key: SUPABASE_ANON_KEY
        value: your-anon-key-here
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: your-service-role-key-here
    autoDeploy: true
